#ifndef _GLAM_DICT_H_
#define _GLAM_DICT_H_

#include <kourier.h>

class GLAM
{
public:
	enum GLAM_MsgID
	{
		MSG_SET,//0
		MSG_REQ,//1
		MSG_ERR,//2
		MSG_EVT,//3
		MSG_TRANS,//4
		MSG_DATA,//5
		MSG_DEL,//6
		MSG_CFG,//7
		MSG_LOCK_INFO,//8
	};

	enum GLAM_TagID
	{
		TAG_KEY_SN,//0
		TAG_KEY_BOX,//1
		TAG_KEY_CELL,//2
		TAG_KEY_PIN,//3
		TAG_KEY_PUK,//4
		TAG_KEY_APN,//5
		TAG_KEY_APN_PASS,//6
		TAG_KEY_APN_USER,//7
		TAG_KEY_SW,//8
		TAG_KEY_HW,//9
		TAG_KEY_INDICATE,//10
		TAG_KEY_BAR,//11
		TAG_KEY_BATTERY,//12
		TAG_EVT_TYPE,//13
		TAG_LOCK_SN,//14
		TAG_LOCK_SEQ,//15
		TAG_LOCK_LAT,//16
		TAG_LOCK_LON,//17
		TAG_LOCK_TIME,//18
		TAG_LOCK_TAG,//19
		TAG_LOCK_STATUS,//20
		TAG_LOCK_OPEN,//21
		TAG_LOCK_CLOSE,//22
		TAG_LOCK_DESC,//23
		TAG_LOCK_TYPE,//24
		TAG_TRANS_TYPE,//25
		TAG_TRANS_START,//26
		TAG_TRANS_END,//27
		TAG_TRANS_RADUIS,//28
		TAG_TRANS_LAT,//29
		TAG_TRANS_LON,//30
		TAG_TRANS_ACK,//31
		TAG_TRANS_CNT,//32
		TAG_TRANS_REQ,//33
		TAG_TRANS_DURESS,//34
		TAG_SRV_NAME,//35
		TAG_SRV_PORT,//36
		TAG_BIN_DATA,//37
		TAG_FILE_NAME,//38
		TAG_FILE_SIZE,//39
		TAG_FILE_PACKET,//40
		TAG_FILE_CRC,//41
		TAG_FILE_VERSION,//42
		TAG_JSON_NAME,//43
		TAG_JSON_PORT,//44
		TAG_KEY_MANUAL,//45
		TAG_GPS_SPOOFING,//46
		TAG_JOB_CARD,//47
		TAG_ID_CLOSE,//48
		TAG_ID_OPEN,//49
		TAG_LOGIC_AND,//50
		TAG_LOGIC_OR,//51
		TAG_LOGIC_END,//52
		TAG_LOCK_INFO,//53
		TAG_LOCK_END,//54
	};

	enum TAG_KEY_INDICATE_Type
	{
		INDICATE_KEY_TRANSFER,//0
		INDICATE_KEY_LOCK,//1
		INDICATE_KEY_ERROR,//2
	};

	enum TAG_EVT_TYPE_Type
	{
		EVENT_KEY_START = 0,
		EVENT_KEY_LOCK_DISCOVERY = 1,
		EVENT_KEY_OPEN_AUTH = 2,
		EVENT_KEY_CLOSE_AUTH = 3,
		EVENT_KEY_CLOSE_AUTH_LATE = 4,
		EVENT_KEY_OPEN_AUTH_CLOSED = 5,
		EVENT_KEY_CLOSE_AUTH_OPENED = 6,
		EVENT_KEY_OPEN_ERROR = 7,
		EVENT_KEY_CLOSE_ERROR = 8,
		EVENT_KEY_OPEN_ATTEMPT = 9,
		EVENT_KEY_CLOSE_ATTEMPT = 10,
		EVENT_KEY_AUTH_COMM_SUCCESS = 11,
		EVENT_KEY_AUTH_COMM_FAILURE = 12,
		EVENT_KEY_OPEN_NOTAG = 13,
		EVENT_KEY_CLOSE_NOTAG = 14,
		EVENT_KEY_TAG_CHECK_ERROR = 15,
		EVENT_KEY_DURESS = 16,
		EVENT_KEY_TAMPER = 17,
		EVENT_KEY_COMMS_FAILURE = 22,
		EVENT_KEY_INIT_COMMS_FAILURE = 25,
		EVENT_KEY_OPEN_AUTH_NO_GPS = 31,
		EVENT_KEY_CLOSE_AUTH_NO_GPS = 32,
		EVENT_KEY_OPEN_AUTH_RADUIS_LRG = 33,
		EVENT_KEY_CLOSE_AUTH_RADUIS_LRG = 34,
		EVENT_KEY_OPEN_AUTH_TIME_INVAL = 35,
		EVENT_KEY_CLOSE_AUTH_TIME_INVAL = 36,
	};

	enum TAG_TRANS_TYPE_Type
	{
		TRANS_TYPE_ACCESS = 1,
		TRANS_TYPE_COMMISSION = 2,
		TRANS_TYPE_ACCESS_COMM = 3,
		TRANS_TYPE_NOAUTH = 4,
		TRANS_TYPE_LATE_AUTH = 5,
		TRANS_TYPE_REPLACE_LATCH = 6,
	};

	static const KourierDictDef *DictDef;
	static const uint8_t dictID;
	static const uint8_t dictVer;
};

#endif
